package sigmaone.industrialism.block.multiblock.machine

import sigmaone.industrialism.Industrialism.Companion.COKE_OVEN_MULTIBLOCK
import sigmaone.industrialism.block.multiblock.BlockEntityMultiblockRootBase

class BlockEntityCokeOvenMultiblock : BlockEntityMultiblockRootBase(COKE_OVEN_MULTIBLOCK)