package sigmaone.industrialism.recipe
import sigmaone.industrialism.Industrialism
import vazkii.patchouli.client.book.page.abstr.PageSimpleProcessingRecipe

class PatchouliPageCoking: PageSimpleProcessingRecipe<CokingRecipe>(Industrialism.COKING_RECIPE_TYPE)